### ISSUE TITLE
Show signature of methods in flame graph

### ISSUE THREAD

**Issue by rgankema** [JuliaPerf/PProf.jl#24]
Right now functions in the flame graph are only identified by their name, and not their signature. That makes it hard to identify exactly which method is called, especially for functions that have many different methods that might delegate work to each other. It would be great if the visualization could be extended to show the argument types :)

**Comment by NHDaly** [comment]
It turns out the problem is in google's `pprof` binary itself, which is pruning away everything starting from the first `(` in the name.

After digging for a while i managed to find the place that does this, but it's not clear if it's easy to change. I've asked about it in an issue, here:
https://github.com/google/pprof/issues/573

**Comment by NHDaly** [comment]
This was closed in #31
