### ISSUE TITLE
Lots of time spent in unknown function swtch_pri

### ISSUE THREAD

**Issue by GlenHenshaw** [JuliaPerf/PProf.jl#39]
Hi there.

I'm profiling a fairly complex scientific code, and the output of pprof() says that about 80% of my execution time is spent in a routine called "swtch_pri". There are no code paths attached to it, and it doesn't show up in Profile.print() at all. Any idea what it is?

![Screen Shot 2021-04-22 at 3 51 42 PM](https://user-images.githubusercontent.com/19539769/115777023-cf10e900-a382-11eb-8844-8291da2f6279.png)

**Comment by NHDaly** [comment]
Hi, sorry we didn't reply for so long.

Based on some googling, it looks like this is a system call in the Mach kernel: https://stackoverflow.com/questions/12119739/where-can-i-find-the-code-of-function-swtch-pri

I believe that this is your operating system's function that implements _waiting_, which is what a thread is doing if it's not running a julia Tasks. So my guess is that since you're seeing 80% of time in that function, you are running with 5 julia threads (`-t 5`), but only doing single threaded work, so only `1/5 == 20%` of your cores are doing anything, and the other `4/5 == 80%` are just idle, which shows up as `swtch_pri` on your operating system. :)

Hope this was helpful, sorry for our very long delay.
